// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: xdp/xdp.proto

package xdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XDPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Len       uint32 `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *XDPRequest) Reset() {
	*x = XDPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xdp_xdp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XDPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XDPRequest) ProtoMessage() {}

func (x *XDPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xdp_xdp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XDPRequest.ProtoReflect.Descriptor instead.
func (*XDPRequest) Descriptor() ([]byte, []int) {
	return file_xdp_xdp_proto_rawDescGZIP(), []int{0}
}

func (x *XDPRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *XDPRequest) GetLen() uint32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *XDPRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type XDPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
}

func (x *XDPResponse) Reset() {
	*x = XDPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xdp_xdp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XDPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XDPResponse) ProtoMessage() {}

func (x *XDPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xdp_xdp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XDPResponse.ProtoReflect.Descriptor instead.
func (*XDPResponse) Descriptor() ([]byte, []int) {
	return file_xdp_xdp_proto_rawDescGZIP(), []int{1}
}

func (x *XDPResponse) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

var File_xdp_xdp_proto protoreflect.FileDescriptor

var file_xdp_xdp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x78, 0x64, 0x70, 0x2f, 0x78, 0x64, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x78, 0x64, 0x70, 0x22, 0x50, 0x0a, 0x0a, 0x58, 0x44, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6c,
	0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x0b, 0x58, 0x44, 0x50, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x32, 0x39, 0x0a, 0x03, 0x58, 0x44, 0x50, 0x12, 0x32, 0x0a, 0x09, 0x58, 0x44,
	0x50, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0f, 0x2e, 0x78, 0x64, 0x70, 0x2e, 0x58, 0x44,
	0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x78, 0x64, 0x70, 0x2e, 0x58,
	0x44, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x23,
	0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x62,
	0x65, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x78, 0x64, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xdp_xdp_proto_rawDescOnce sync.Once
	file_xdp_xdp_proto_rawDescData = file_xdp_xdp_proto_rawDesc
)

func file_xdp_xdp_proto_rawDescGZIP() []byte {
	file_xdp_xdp_proto_rawDescOnce.Do(func() {
		file_xdp_xdp_proto_rawDescData = protoimpl.X.CompressGZIP(file_xdp_xdp_proto_rawDescData)
	})
	return file_xdp_xdp_proto_rawDescData
}

var file_xdp_xdp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xdp_xdp_proto_goTypes = []interface{}{
	(*XDPRequest)(nil),  // 0: xdp.XDPRequest
	(*XDPResponse)(nil), // 1: xdp.XDPResponse
}
var file_xdp_xdp_proto_depIdxs = []int32{
	0, // 0: xdp.XDP.XDPStream:input_type -> xdp.XDPRequest
	1, // 1: xdp.XDP.XDPStream:output_type -> xdp.XDPResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xdp_xdp_proto_init() }
func file_xdp_xdp_proto_init() {
	if File_xdp_xdp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xdp_xdp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XDPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xdp_xdp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XDPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xdp_xdp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xdp_xdp_proto_goTypes,
		DependencyIndexes: file_xdp_xdp_proto_depIdxs,
		MessageInfos:      file_xdp_xdp_proto_msgTypes,
	}.Build()
	File_xdp_xdp_proto = out.File
	file_xdp_xdp_proto_rawDesc = nil
	file_xdp_xdp_proto_goTypes = nil
	file_xdp_xdp_proto_depIdxs = nil
}
