// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: xdp/xdp.proto

package xdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetXDPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
}

func (x *GetXDPRequest) Reset() {
	*x = GetXDPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xdp_xdp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXDPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXDPRequest) ProtoMessage() {}

func (x *GetXDPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xdp_xdp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXDPRequest.ProtoReflect.Descriptor instead.
func (*GetXDPRequest) Descriptor() ([]byte, []int) {
	return file_xdp_xdp_proto_rawDescGZIP(), []int{0}
}

func (x *GetXDPRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type GetXDPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcIP   uint32 `protobuf:"varint,1,opt,name=SrcIP,proto3" json:"SrcIP,omitempty"`
	DstIP   uint32 `protobuf:"varint,2,opt,name=DstIP,proto3" json:"DstIP,omitempty"`
	SrcPort uint32 `protobuf:"varint,3,opt,name=SrcPort,proto3" json:"SrcPort,omitempty"`
	DstPort uint32 `protobuf:"varint,4,opt,name=DstPort,proto3" json:"DstPort,omitempty"`
	Seq     uint32 `protobuf:"varint,5,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Ack     uint32 `protobuf:"varint,6,opt,name=Ack,proto3" json:"Ack,omitempty"`
	Flags   uint32 `protobuf:"varint,7,opt,name=Flags,proto3" json:"Flags,omitempty"`
	Window  uint32 `protobuf:"varint,8,opt,name=Window,proto3" json:"Window,omitempty"`
}

func (x *GetXDPResponse) Reset() {
	*x = GetXDPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xdp_xdp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXDPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXDPResponse) ProtoMessage() {}

func (x *GetXDPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xdp_xdp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXDPResponse.ProtoReflect.Descriptor instead.
func (*GetXDPResponse) Descriptor() ([]byte, []int) {
	return file_xdp_xdp_proto_rawDescGZIP(), []int{1}
}

func (x *GetXDPResponse) GetSrcIP() uint32 {
	if x != nil {
		return x.SrcIP
	}
	return 0
}

func (x *GetXDPResponse) GetDstIP() uint32 {
	if x != nil {
		return x.DstIP
	}
	return 0
}

func (x *GetXDPResponse) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *GetXDPResponse) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *GetXDPResponse) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetXDPResponse) GetAck() uint32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *GetXDPResponse) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *GetXDPResponse) GetWindow() uint32 {
	if x != nil {
		return x.Window
	}
	return 0
}

var File_xdp_xdp_proto protoreflect.FileDescriptor

var file_xdp_xdp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x78, 0x64, 0x70, 0x2f, 0x78, 0x64, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x78, 0x64, 0x70, 0x22, 0x2d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x58, 0x44, 0x50, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x22, 0xc2, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x58, 0x44, 0x50, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x72, 0x63, 0x49, 0x50, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x72, 0x63, 0x49, 0x50, 0x12, 0x14, 0x0a, 0x05,
	0x44, 0x73, 0x74, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x44, 0x73, 0x74,
	0x49, 0x50, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x53, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x44, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x44,
	0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x71, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6c,
	0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x46, 0x6c, 0x61, 0x67, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x32, 0x45, 0x0a, 0x03, 0x58, 0x44, 0x50, 0x12,
	0x3e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x12, 0x2e, 0x78, 0x64, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x44, 0x50, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x78, 0x64, 0x70, 0x2e, 0x47, 0x65, 0x74,
	0x58, 0x44, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75,
	0x62, 0x65, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x78, 0x64, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xdp_xdp_proto_rawDescOnce sync.Once
	file_xdp_xdp_proto_rawDescData = file_xdp_xdp_proto_rawDesc
)

func file_xdp_xdp_proto_rawDescGZIP() []byte {
	file_xdp_xdp_proto_rawDescOnce.Do(func() {
		file_xdp_xdp_proto_rawDescData = protoimpl.X.CompressGZIP(file_xdp_xdp_proto_rawDescData)
	})
	return file_xdp_xdp_proto_rawDescData
}

var file_xdp_xdp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xdp_xdp_proto_goTypes = []interface{}{
	(*GetXDPRequest)(nil),  // 0: xdp.GetXDPRequest
	(*GetXDPResponse)(nil), // 1: xdp.GetXDPResponse
}
var file_xdp_xdp_proto_depIdxs = []int32{
	0, // 0: xdp.XDP.GetPacketStream:input_type -> xdp.GetXDPRequest
	1, // 1: xdp.XDP.GetPacketStream:output_type -> xdp.GetXDPResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xdp_xdp_proto_init() }
func file_xdp_xdp_proto_init() {
	if File_xdp_xdp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xdp_xdp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXDPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xdp_xdp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXDPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xdp_xdp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xdp_xdp_proto_goTypes,
		DependencyIndexes: file_xdp_xdp_proto_depIdxs,
		MessageInfos:      file_xdp_xdp_proto_msgTypes,
	}.Build()
	File_xdp_xdp_proto = out.File
	file_xdp_xdp_proto_rawDesc = nil
	file_xdp_xdp_proto_goTypes = nil
	file_xdp_xdp_proto_depIdxs = nil
}
