// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: xdp/xdp.proto

package xdp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XDPClient is the client API for XDP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XDPClient interface {
	XDPStream(ctx context.Context, opts ...grpc.CallOption) (XDP_XDPStreamClient, error)
}

type xDPClient struct {
	cc grpc.ClientConnInterface
}

func NewXDPClient(cc grpc.ClientConnInterface) XDPClient {
	return &xDPClient{cc}
}

func (c *xDPClient) XDPStream(ctx context.Context, opts ...grpc.CallOption) (XDP_XDPStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &XDP_ServiceDesc.Streams[0], "/xdp.XDP/XDPStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &xDPXDPStreamClient{stream}
	return x, nil
}

type XDP_XDPStreamClient interface {
	Send(*XDPRequest) error
	CloseAndRecv() (*XDPResponse, error)
	grpc.ClientStream
}

type xDPXDPStreamClient struct {
	grpc.ClientStream
}

func (x *xDPXDPStreamClient) Send(m *XDPRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *xDPXDPStreamClient) CloseAndRecv() (*XDPResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(XDPResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// XDPServer is the server API for XDP service.
// All implementations must embed UnimplementedXDPServer
// for forward compatibility
type XDPServer interface {
	XDPStream(XDP_XDPStreamServer) error
	mustEmbedUnimplementedXDPServer()
}

// UnimplementedXDPServer must be embedded to have forward compatible implementations.
type UnimplementedXDPServer struct {
}

func (UnimplementedXDPServer) XDPStream(XDP_XDPStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method XDPStream not implemented")
}
func (UnimplementedXDPServer) mustEmbedUnimplementedXDPServer() {}

// UnsafeXDPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XDPServer will
// result in compilation errors.
type UnsafeXDPServer interface {
	mustEmbedUnimplementedXDPServer()
}

func RegisterXDPServer(s grpc.ServiceRegistrar, srv XDPServer) {
	s.RegisterService(&XDP_ServiceDesc, srv)
}

func _XDP_XDPStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(XDPServer).XDPStream(&xDPXDPStreamServer{stream})
}

type XDP_XDPStreamServer interface {
	SendAndClose(*XDPResponse) error
	Recv() (*XDPRequest, error)
	grpc.ServerStream
}

type xDPXDPStreamServer struct {
	grpc.ServerStream
}

func (x *xDPXDPStreamServer) SendAndClose(m *XDPResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *xDPXDPStreamServer) Recv() (*XDPRequest, error) {
	m := new(XDPRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// XDP_ServiceDesc is the grpc.ServiceDesc for XDP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XDP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xdp.XDP",
	HandlerType: (*XDPServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "XDPStream",
			Handler:       _XDP_XDPStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "xdp/xdp.proto",
}
